// <auto-generated />
using System;
using Backend_Frock.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_Frock.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend_Frock.Companies.Domain.Model.Aggregates.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("invitation_code");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_companies");

                    b.HasIndex("FkIdUser")
                        .IsUnique()
                        .HasDatabaseName("i_x_companies_fk_id_user");

                    b.HasIndex("InvitationCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_companies_invitation_code");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Backend_Frock.Companies.Domain.Model.Aggregates.CompanyMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<int>("MemberRole")
                        .HasColumnType("int")
                        .HasColumnName("member_role");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_company_memberships");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_company_memberships_user_id");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_company_memberships_company_id_user_id");

                    b.ToTable("company_memberships");
                });

            modelBuilder.Entity("Backend_Frock.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Backend_Frock.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DriverEarnings")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("driver_earnings");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<string>("PaypalTransactionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("paypal_transaction_id");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("platform_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_reservations");

                    b.HasIndex("PaypalTransactionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_reservations_paypal_transaction_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_reservations_user_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Reservations.Domain.Model.Aggregates.ReservationRoute", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.HasKey("ReservationId", "RouteId")
                        .HasName("p_k_reservation_routes");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_reservation_routes_route_id");

                    b.ToTable("reservation_routes", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Aggregates.RouteAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Entities.RoutesStops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FKRouteId")
                        .HasColumnType("int")
                        .HasColumnName("f_k_route_id");

                    b.Property<int>("FkStopId")
                        .HasColumnType("int")
                        .HasColumnName("fk_stop_id");

                    b.HasKey("Id")
                        .HasName("p_k_route_stops");

                    b.HasIndex("FKRouteId")
                        .HasDatabaseName("i_x_route_stops_f_k_route_id");

                    b.HasIndex("FkStopId")
                        .HasDatabaseName("i_x_route_stops_fk_stop_id");

                    b.ToTable("route_stops", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("end_time");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("p_k_schedules");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_schedules_route_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FkIdProvince")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_province");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_districts");

                    b.HasIndex("FkIdProvince")
                        .HasDatabaseName("i_x_districts_fk_id_province");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FkIdRegion")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_region");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_provinces");

                    b.HasIndex("FkIdRegion")
                        .HasDatabaseName("i_x_provinces_fk_id_region");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_regions");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("FkIdCompany")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_company");

                    b.Property<int>("FkIdDistrict")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_district");

                    b.Property<string>("GoogleMapsUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("google_maps_url");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("p_k_stops");

                    b.HasIndex("FkIdCompany")
                        .HasDatabaseName("i_x_stops_fk_id_company");

                    b.HasIndex("FkIdDistrict")
                        .HasDatabaseName("i_x_stops_fk_id_district");

                    b.ToTable("stops");
                });

            modelBuilder.Entity("Backend_Frock.Subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("PaypalPlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("paypal_plan_id");

                    b.Property<string>("PaypalSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("paypal_subscription_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Backend_Frock.Companies.Domain.Model.Aggregates.Company", b =>
                {
                    b.HasOne("Backend_Frock.IAM.Domain.Model.Aggregates.User", null)
                        .WithOne()
                        .HasForeignKey("Backend_Frock.Companies.Domain.Model.Aggregates.Company", "FkIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_companies__users_fk_id_user");
                });

            modelBuilder.Entity("Backend_Frock.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.HasOne("Backend_Frock.IAM.Domain.Model.Aggregates.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reservations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_Frock.Reservations.Domain.Model.Aggregates.ReservationRoute", b =>
                {
                    b.HasOne("Backend_Frock.Reservations.Domain.Model.Aggregates.Reservation", "Reservation")
                        .WithMany("ReservationRoutes")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reservation_routes_reservations_reservation_id");

                    b.HasOne("Backend_Frock.Routes.Domain.Model.Aggregates.RouteAggregate", "Routes")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reservation_routes__routes_route_id");

                    b.Navigation("Reservation");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Entities.RoutesStops", b =>
                {
                    b.HasOne("Backend_Frock.Routes.Domain.Model.Aggregates.RouteAggregate", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("FKRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_route_stops_routes_f_k_route_id");

                    b.HasOne("Backend_Frock.Stops.Domain.Model.Aggregates.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("FkStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_route_stops__stops_fk_stop_id");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Entities.Schedule", b =>
                {
                    b.HasOne("Backend_Frock.Routes.Domain.Model.Aggregates.RouteAggregate", null)
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_schedules_routes_route_id");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.District", b =>
                {
                    b.HasOne("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.Province", null)
                        .WithMany()
                        .HasForeignKey("FkIdProvince")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_districts__provinces_fk_id_province");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.Province", b =>
                {
                    b.HasOne("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.Region", null)
                        .WithMany()
                        .HasForeignKey("FkIdRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_provinces__regions_fk_id_region");
                });

            modelBuilder.Entity("Backend_Frock.Stops.Domain.Model.Aggregates.Stop", b =>
                {
                    b.HasOne("Backend_Frock.Companies.Domain.Model.Aggregates.Company", null)
                        .WithMany()
                        .HasForeignKey("FkIdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_stops_companies_fk_id_company");

                    b.HasOne("Backend_Frock.Stops.Domain.Model.Aggregates.Geographic.District", null)
                        .WithMany()
                        .HasForeignKey("FkIdDistrict")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_stops_districts_fk_id_district");
                });

            modelBuilder.Entity("Backend_Frock.Reservations.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Navigation("ReservationRoutes");
                });

            modelBuilder.Entity("Backend_Frock.Routes.Domain.Model.Aggregates.RouteAggregate", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
